### ISSUE TITLE
what‘s the meaning of depth

### ISSUE THREAD

**Issue by xiaomouse2004** [ethz-asl/rovio#100]
Hi: 
      I'm debugging the code of rovio. However I find something I can't explain. After the initialization the camera_inertial module, i move the module along one direction(eg: the y axis expressed in  the inertial world coordinate), I find that the depth changes a lot. I print the depth in the terminator. After the initialization it always between 0.6 - 0.7, However When I move the module, it will change to about 4.0 or more bigger. And at this time I always get the divergences of the pose of odometry however the patch of image is stable when I stop the moving. Besides, if I leave the module still, the depth will change bigger and bigger at a very slow velocity. Please tell me the reason of divergences of depth and what's the meaning of depth. Thank you very much. ps: I use a monocular camera（OV7251） with the resolution of 320*240 and the imu is MPU9250.
      I also record a dataset which maybe help. First I move the module in the negative direction of y axis and after about -30cm I stop. Next I move the module in the positive direction of y axis with the distance of 30cm. So I move to the origin, then I move the module in the negative of x axis with the distance of 20cm, and after that I move it in the positive of x axis with the distance of 20cm. At last I move the module in the positive of z axis with the distance of 20cm and after that in the positive of z axis with the distance of 20cm.
      I upload the dataset to the network disk.The website is 
https://drive.google.com/file/d/0B-PMqIY7Px04ZXljbTcwSk1IYXc/view?usp=sharing.
      Please download it and help me to solve the problem. Thank you very much.

**Comment by bloesch** [comment]
In monocular vision, the distance (depth) to landmarks is not observable from a single view and that it why it drift if there is no motion, and converges as soon as you move.

Divergence issues have been extensively discussed in previous issues. Please look at them. A brief summary can also be found under https://github.com/ethz-asl/rovio/wiki/Divergence

Also, your dataset is not very useful if you do not provide any extrinsics/intrincs or IMU specs.
