### ISSUE TITLE
unknown error message

### ISSUE THREAD

**Issue by Kyle-ak** [ethz-asl/rovio#101]
When I run the command `roslaunch rovio rovio_rosbag_node.launch` I always get the error message:

==== Model jacInput Test failed: 74.0615 is larger than 1 at row 1(def_0) and col 0() ====
  -72871.9  -72797.9

I did a little bit search among the previous Issues. It seems that it's related to IMU data? BTW, I managed to get visual features:
![screenshot from 2016-12-23 18 27 17](https://cloud.githubusercontent.com/assets/13564326/21451873/8658e164-c93d-11e6-9b46-c4cac68a79c8.png)

rosbag is downloaded from EUROC dataset, and I already checked it, it's not corrupted.

**Comment by bloesch** [comment]
there is a comment above the error mentioning that this may be normal due to the limited precision of the finite difference Jacobian test.

**Comment by Kyle-ak** [comment]
@bloesch my bad, didn't read the message carefully. Thanks for your reply, and this awesome project 👍
