### ISSUE TITLE
About inverse depth and the bearing vector propagating formula

### ISSUE THREAD

**Issue by xiaopenghuang** [ethz-asl/rovio#102]
Hi all,
I spent a lot time in understand the following formula,
![1111](https://cloud.githubusercontent.com/assets/7861326/21471363/25a933be-caeb-11e6-993e-9e5784795213.png)
But i still cannot get it; Any one can tell me how to derivate the formula, any paper or clue.
Thank you.

**Comment by bloesch** [comment]
Those are the minimal derivatives of bearing vector and distance parameter. The derivation of the bearing vector is more involved - a journal paper providing more insights is currently under review. The distance parameter derivative is slightly more intuitiv. If "rho" is the distance parameter and "d" the actual distance you can write:
> drho/dt = drho/dd * dd/dt

with:
> drho/dd = 1/(dd/drho)
> dd/dt = - mu^T v

The last derivative basically states that the change in distance is equivalent to the velocity of the camera projected onto the bearing vector of the landmark of interest.

**Comment by xiaopenghuang** [comment]
Thanks , can you estimate how long the journal could publish.

**Comment by bloesch** [comment]
difficult to estimate. around 1-2 months.

**Comment by xiaopenghuang** [comment]
thanks

**Comment by xiaopenghuang** [comment]
@bloesch can i get the journal paper now.

**Comment by bloesch** [comment]
still under review.

**Comment by xiaopenghuang** [comment]
@bloesch can you provide some clue about bearing vector formula. The journal still under review...
