### ISSUE TITLE
Ubuntu Xenial crashing still not resolved

### ISSUE THREAD

**Issue by ojura** [ethz-asl/rovio#103]
Hi. I know that it's really getting old with this bug, but I am still having having issues which you thought were resolved in #94. I have just verified that on a fresh Ubuntu 16.04.1 with ROS kinetic, the most recent version of Rovio (at the time of writing 33307527), with checked out lightweight_filtering @ b1d235d, crashes:

<details>
  <summary>Crash log</summary>
[ INFO] [1484063952.158803099]: Recording to /home/juraj/catkin_ws/src/vslam_evaluation/out/rovio_traj.bag.

Set Camera Matrix to:
458.654       0 367.215
      0 457.296 248.375
      0       0       1

Set distortion parameters (Radtan) to: k1(-0.283408), k2(0.0739591), k3(0), p1(0.00019359), p2(1.76187e-05)

Testing Prediction

==== Test successful (7.65383e-08) ====

==== Test successful (8.86546e-08) ====

Testing cameraOutputCF

==== Test successful (6.36613e-08) ====

Testing imuOutputCF

==== Test successful (1.27552e-08) ====

Testing attitudeToYprCF

==== Test successful (6.43838e-08) ====

Testing transformFeatureOutputCT

==== Test successful (1.44278e-08) ====

Testing LandmarkOutputImuCT

==== Test successful (2.5853e-08) ====

Testing FeatureOutputReadableCT

==== Test successful (1.47619e-08) ====

Testing pixelOutputCT (can sometimes exhibit large absolut errors due to the float precision)

==== Model jacInput Test failed: 74.0615 is larger than 1 at row 1(def_0) and col 0() ====

  -72871.9  -72797.9

Testing zero velocity update

==== Test successful (1.39778e-10) ====

==== Test successful (1.39778e-10) ====

-- Filter: Initializing using accel. measurement ...

-- Filter: Initialized at t = 1403715273.26

[FilterBase::addUpdateMeas] Warning: included measurements at time 1403715273.26 before safeTime 1403715273.26

init done

[rovio-2] process has died [pid 12186, exit code -11, cmd /home/juraj/catkin_ws/devel/lib/rovio/rovio_node __name:=rovio __log:=/home/juraj/.ros/log/ba257322-d74d-11e6-8ab3-f0def1de224c/rovio-2.log].

log file: /home/juraj/.ros/log/ba257322-d74d-11e6-8ab3-f0def1de224c/rovio-2*.log
</details>

I'm using the EUROC bag ``V1_01_easy.bag`` and this [launch file](https://gist.github.com/ojura/d9838fe48739598c6335816400d65a12) to run Rovio.

I am running Rovio on a Thinkpad T520 with Core i7-2670QM. I build it with `catkin build rovio -j8 --cmake-args -DCMAKE_BUILD_TYPE=Release`. 

As before, adding `add_definitions(-DEIGEN_DONT_ALIGN_STATICALLY)` to CMakeLists fixes the issue and Rovio doesn't crash anymore.

**Comment by nicolov** [comment]
Can you try #119 ?
