### ISSUE TITLE
Example how to hardware-synchronize camera and IMU (mvBlueFox-MLC200wG, MPU6050)

### ISSUE THREAD

**Issue by greymfm** [ethz-asl/rovio#106]
Hello,

As I could not find any tutorial how to hardware-synchronize camera and IMU, I have documented my steps here (it's for a specific hardware however you should be able to use it for other hardware as well):
http://grauonline.de/wordpress/?page_id=1951

Feel free to add a link to the Wiki? :)

Regards,
Alexander

**Comment by bloesch** [comment]
Thank you very much! I am glad to add the link to the wiki.
