### ISSUE TITLE
Response to gazebo image stream

### ISSUE THREAD

**Issue by devbharat** [ethz-asl/rovio#11]
I am trying to run the ROVIO pipeline on the Imu + Vision stream coming from the gazebo iris model's vi-sensor from rotorSimulator(to eventually use the pose update from ROVIO in the feedback loop with pixhawk SITL).

The estimator seems to diverge for simple hovering datasets in a few seconds. I have updated the .yaml files and the rovio.info file to use the calibration file of the gazebo's camera, and to set the camera-IMU transformation (it's identity). The image scenery is fairly textured (though planar), and the detector finds and tracks features for a while, before the depth uncertainty blows up. 

I have rovio running decently on other "real" vi-sensor datasets, and the one difference I see with the image stream coming out of gazebo is that the framerate varies a lot(see https://github.com/ethz-asl/rotors_simulator/issues/277). Could this cause the estimator to blow up ?

**Comment by devbharat** [comment]
The time stamps for both IMU and camera are the gazebosim time, but they run in independent threads.
I'l send you the dataset, it'll be would be great if you could have a look at it.

**Comment by bloesch** [comment]
What is the status? Did you manage to make it run in Gazebo? Did you talk with @raghavkhanna? After adapting the extrinsics/intrinsics he got it working pretty quickly in Gazebo...

**Comment by devbharat** [comment]
Yes, It works almost perfectly. Here are some plots comparing against ground truth:

Rotation Rates:
![rx](https://cloud.githubusercontent.com/assets/3105122/11185628/f2b31df0-8c7d-11e5-825b-eb28a03dcb35.png)
![ry](https://cloud.githubusercontent.com/assets/3105122/11185632/f4cab17a-8c7d-11e5-9fba-26abd15969ae.png)
![rz](https://cloud.githubusercontent.com/assets/3105122/11185637/f77f0718-8c7d-11e5-8433-f24315e23dd1.png)

Linear Velocities:
![vx](https://cloud.githubusercontent.com/assets/3105122/11185647/07c11d46-8c7e-11e5-824c-d8db7abbec84.png)
![vy](https://cloud.githubusercontent.com/assets/3105122/11185649/098f5f66-8c7e-11e5-9d9f-89db2e5baff7.png)
![vz](https://cloud.githubusercontent.com/assets/3105122/11185651/0c2a1e6e-8c7e-11e5-964b-331e63d670d0.png)

Positions:
![x](https://cloud.githubusercontent.com/assets/3105122/11185660/18c35d8e-8c7e-11e5-8971-83bc0cdbfd7c.png)
![y](https://cloud.githubusercontent.com/assets/3105122/11185665/1d0584da-8c7e-11e5-82af-25131caa6e61.png)
![z](https://cloud.githubusercontent.com/assets/3105122/11185668/1eab420c-8c7e-11e5-9eec-7ca2e4ed55c9.png)

Except for position in Z, which isn't that good. I saw a little better position tracking in other gazebo bag files, but it was never perfect.

Here is a link to a screen capture video showing the complete setup:
https://vimeo.com/144726358

**Comment by bloesch** [comment]
Thanks you very much for the feedback! Especially when looking at the velocity estimates it seems like something could be wrong with the corodinate frames during evaluation. I am not sure which of the rovio outputs you are using for your plots, but some will be with respect to the IMU CF and others will be w.r.t the camera CF. If something is mixed up there it could lead to such behavior.

A student of mine is currently writing a python alignment tool (for rosbags), if you are interested I can give you the link as soon as it is ready.

**Comment by devbharat** [comment]
I used rovio/odometry outputs for the plots. Can you tell me which ones are they respect to ? Ideally, we we should be using the ones with respect to IMU coordinate frame for controls, isn't it ? Yes, I'd be interested in the python script! In return, if someone wants to have the px4-sitl-rovio setup to quickly run rovio realtime on a flying quad, I could help set it up.

**Comment by bloesch** [comment]
rovio/pose, rovio/output and rovio/odometry express the motion of the camera w.r.t. the inertial frame. rovio/transform is the IMU w.r.t. the inertial frame.

I see that the output is a bit of a mess, i'll try to clean it up, also i will provide the covariance of the output.

**Comment by bloesch** [comment]
And yes, the output of the IMU is probably the best to use for control (it is also the one which is actually estimated in ROVIO).

One more thing: did you check out the newest version? There was one version which was less stable/accurate. The current one is definetely better.

**Comment by devbharat** [comment]
@bloesch Yes, ploting the ground truth vs rovio/transform removes most of the constant offsets in position and angles! For the linear and angular velocities, the ones published in /rovio/odometry, are they again with respect to Camera CF ? Where should I access the rates wrt the IMU frame ?

Pitch Angle (Red is Ground Truth, Blue is Camera Frame, Green is IMU frame)
![eulerztf](https://cloud.githubusercontent.com/assets/3105122/11210322/bba45f18-8d27-11e5-8ea0-9c0e91fdceec.png)

**Comment by bloesch** [comment]
/rovio/odometry is currently containing the estimate of the camera CF, I will change this to the IMU CF in the next pull request (today sometime)... then you should be able to access the rates of the IMU

**Comment by bloesch** [comment]
Just merged the PR, now the rovio node output should be better. Except for the tf everything is w.r.t. the IMU CF now. Also, if you want to have a look at the post-processing tool please have a look at the following repo:
https://github.com/ethz-asl/trajectory_toolkit
It is not yet fully finished but you can already use it for doing a lot of plots, there is an example.py as well as a rovio specific python script. It should be more or less self explanatory.

**Comment by devbharat** [comment]
Thanks! I'll try out the post-processing tool tonight. I will also have rovio in the loop for controls in the simulation(initially only use rovio's position output, then use the full pose).

One last thing, could you tell me if the external pose input (gps/tag-based etc) to rovio's estimator, is that already in master ? Thanks!

**Comment by bloesch** [comment]
The exteral pose input support is already in the master branch. Unfortunately its not really well documented. It is turned on a soon as the listeners get messages. Thereis an extra calibration which can be turned on to automatically align the different body frames and inertial frames. There are three modes which you can set by setting the nPose cmake variable. if set to 0 no extra calibratiob is performed. if set to 1 the inertial frames CFs are automatically calibrated. if set to 2 the inertial and body-fixed CFs are calibrated.

I will be on holidays for the next three weeks with limited internet connection. If you have questions regarding the external measurements please contact @raghavkhanna

**Comment by devbharat** [comment]
I'll close this issue here, the original problem with gazebo stream(caused by inaccurate Camera CF - IMU CF initialization) is resolved.

**Comment by zz1120122573** [comment]
Hi，I‘m running rovio, but I don't know how to output the pose, could you tell me? Thanks a lot.

**Comment by anastaga** [comment]
@devbharat Hello, as i've understood, you used IMU and Camera and managed to synchronized them. Can you share your methodology or link your repo (if there is one)?
