### ISSUE TITLE
Is it necessary to hardware-synchronize camera and IMU?

### ISSUE THREAD

**Issue by JianXingChen** [ethz-asl/rovio#118]
I can get the timestamp of  IMU(which i used MTI) and  Camera which stored in the sensor_msgs/Image/header  and  sensor_msgs/Imu/header .  if i launch usb_cam_node and xsens_node in the same launch file . is it ok for rovio?

**Comment by bloesch** [comment]
I am not sure I fully understand you question. All timestamps you pass to rovio must be expressed w.r.t. the same clock. How you achieve this does not matter to rovio. Also, this is pretty much independent of how you launch your nodes.

This topic has sufficiently been discussed in previous posts and there is some information at https://github.com/ethz-asl/rovio/wiki/Timing. Closing.
