### ISSUE TITLE
Effects of rolling shutter cameras

### ISSUE THREAD

**Issue by ParthaEth** [ethz-asl/rovio#123]
Hi,

I am trying to use ROVIO with a rolling shutter camera. Specifically an Android phone. Currently I am having trouble making it stable. In your opinion how big might the contribution of rolling shutter might be in breaking the code. 

I know that the time stamps in my system are not particularly very good as I use system time stamp when a camera callback is made so could that be the biggest contributor to instability?

**Comment by bloesch** [comment]
The effect a rolling shutter camera has is related to the topic of bad timestamping. In both cases part of the sensor information does not match with the timestamp it is provided with. The magnitude of the effect on the sensor fusion process is then dependent on the actual motion. For instance if your system is stationary you won't notice any performance degradation (except for unobservability issues).

All in all you should always try to get good timings. In your case it is difficult to say whether it is the rolling shutter camera or the bad timestamps which cause the instability.
