### ISSUE TITLE
Imu get sudden strike, the acceleration is soaring, then odometry diverged

### ISSUE THREAD

**Issue by xiaopenghuang** [ethz-asl/rovio#125]
![screenshot from 2017-06-13 11 02 38](https://user-images.githubusercontent.com/7861326/27064064-d6bd1d66-5027-11e7-8308-884a84d3d27e.png)

this is the imu read from a quadrotor , when the quadrotor hit the groud ,we can see the acceleration can soar up to 70m.s^-2 , then the formula calculate the velocity is so big .But the image update process  cannot reduce velocity soaring, 
how can make image update process take more roles in such situation or just drop the imu measures which  beyond a certain value.

**Comment by bloesch** [comment]
This strong spikes in IMU reading do represent a problem for Rovio. Unfortunately, a classical Kalman filter does not allow to detect outliers in measurements related to the prediction model. You could try to do some manual outlier detection before passing the messages to Rovio. E.g., set maximal values for the acceleration or pre-filter them with some sort of low-pass.
