### ISSUE TITLE
Some bugs when running Euroc rosbag, the result is bad

### ISSUE THREAD

**Issue by AlsonXiong** [ethz-asl/rovio#126]
I installed rovio opensource and its Dependencies successfully  in Ubuntu 14.04.  But When I download Euroc rosbag and run rovio on mono camera mode,  the running result is abnormal and bad.  What is the reason about this problem ? Is there a requirement for the Dependencies  version ?

**Comment by bloesch** [comment]
That does not sound right. It should be working on the euroc rosbag and I doubt that this is caused by any wrong dependencies.
