### ISSUE TITLE
Derivations of Equation 9 and Equation 10 in the paper

### ISSUE THREAD

**Issue by BITVoyager** [ethz-asl/rovio#129]
Hi. Could you please provide any insights on the derivations of Equation 9 and Equation 10 in the paper? Thank you.

**Comment by bloesch** [comment]
There will be some more details in a journal paper that should get accessible this month. I will link it as soon as its available online.

**Comment by BITVoyager** [comment]
Cool. Thank you. Do you have a short answer to this question? :-)

**Comment by bloesch** [comment]
I do not think there is a short answer to this. What I did is introduce a parametrization for unit vectors together with a representation of differences between them. The differentials then can be derived by looking at the limit of small perturbations on those unit vectors (similar to the classical derivation of differentials)...

**Comment by bloesch** [comment]
I link to the IJRR paper is provided in the README. Hope that helps.

**Comment by BITVoyager** [comment]
@bloesch Thank you.
