### ISSUE TITLE
predictMergedEKF mean measurement error

### ISSUE THREAD

**Issue by stihuangyuan** [ethz-asl/rovio#132]
thanks for your great work. When i look into imu predict,  calculate mean measurent
`double t = itMeasStart->first;
        for(typename std::map<double,mtMeas>::const_iterator itMeas=next(itMeasStart); itMeas!=itMeasEnd; itMeas++)
        {
            itMeasStart->second.boxMinus(itMeas->second,difVec);
            vec = vec + difVec*(std::min(itMeas->first,tTarget)-t);
            t = std::min(itMeas->first,tTarget);
        }
        vec = vec/dT;
        itMeasStart->second.boxPlus(vec,meanMeas);`
is there a symbol error? maybe it should be this?
`itMeasStart->second.boxMinus(vec,meanMeas);`

**Comment by bloesch** [comment]
It looks like there is a sign error there. The third line should do itMeas - itMeasStart and not the other way round. I will check this and create a PR. Thanks for the catch.

**Comment by bloesch** [comment]
see #133. Thanks again!
