### ISSUE TITLE
n.getM() in bearingToPixel

### ISSUE THREAD

**Issue by liucsg** [ethz-asl/rovio#137]
Hi bloesch!
As I understand, Camera::bearingToPixel is doing projection(3D -> 2D), I do not know what is mean of n.getM(). Could you help giving some guidance on this item?
Thanks

**Comment by bloesch** [comment]
getM returns two perpendicular directions to the bearing vector n. Relating to http://dx.doi.org/10.1177/0278364917728574 , it represents a rotated version of the matrix N. It is used to parametrize local perturbations on the bearing vector n.

**Comment by liucsg** [comment]
bool Camera::bearingToPixel(const LWF::NormalVectorElement& n, cv::Point2f& c, Eigen::Matrix<double,2,2>& J) const{
Eigen::Matrix<double,3,2> J1;
J1 = n.getM();
Eigen::Matrix<double,2,3> J2;
const bool success = bearingToPixel(n.getVec(),c,J2);
J = J2*J1;
return success;
}

Hi bloesch,
I know the mean of J2. Could you tell me that why J is equal to J2*J1 In this function?
Thanks!

At 2017-12-01 17:53:13, "bloesch" <notifications@github.com> wrote:


getM returns two perpendicular directions to the bearing vector n. Relating to http://dx.doi.org/10.1177/0278364917728574 , it represents a rotated version of the matrix N. It is used to parametrize local perturbations on the bearing vector n.

**Comment by bloesch** [comment]
This is the chain rule:

J2: d(pixel)/d(global coordinates)
J1: d(global coordinates)/d(local coordinates)
=> J = d(pixel)/d(local coordinates)

If you are not familiar with the concept of local/global coordinates the following may help:
- http://asrl.utias.utoronto.ca/~tdb/bib/barfoot_ser17.pdf
- http://ceres-solver.org/nnls_modeling.html#localparameterization
- https://arxiv.org/abs/1606.05285

**Comment by liucsg** [comment]
Thank you very much!

At 2017-12-04 16:43:09, "bloesch" <notifications@github.com> wrote:


This is the chain rule:

J2: d(pixel)/d(global coordinates)
J1: d(global coordinates)/d(local coordinates)
=> J = d(pixel)/d(local coordinates)

If you are not familiar with the concept of local/global coordinates the following may help:

http://asrl.utias.utoronto.ca/~tdb/bib/barfoot_ser17.pdf
http://ceres-solver.org/nnls_modeling.html#localparameterization
https://arxiv.org/abs/1606.05285
