### ISSUE TITLE
How much is it the accuracy?

### ISSUE THREAD

**Issue by realitian** [ethz-asl/rovio#142]
Hi
please share about the accuracy with monocular camera and imu.
is there no drift?

**Comment by bloesch** [comment]
There is no single number describing accuracy. See the papers for a detailed evaluation. Also the accuracy is strongly depending on the system (camera/IMU), the quality of the calibration, and the dataset you test it on....

There is not loop closure in rovio. See https://github.com/ethz-asl/maplab for drift-free localisation.
