### ISSUE TITLE
roslaunch error

### ISSUE THREAD

**Issue by cumtchenchang** [ethz-asl/rovio#145]
I am so  sorry to disturb you.
 I set the  dataset path in rovio_rosbag_node.launch as:
  param name="rosbag_filename" value="/home/cc/data/euroc/MH_03_medium.bag"/

when I input cc@cc-B250-HD3:~/rovio_ws$ roslaunch rovio  rovio_rosbag_node.launch 
get one error:
Recording
Storing output to: /home/cc/data/euroc/rovio/2018-01-11-02-19-39_25_4_6_1_0.bag
terminate called after throwing an instance of 'rosbag::BagIOException'
  what():  Error opening file: /home/cc/data/euroc/rovio/2018-01-11-02-19-39_25_4_6_1_0.bag
[rovio-2] process has died [pid 3454, exit code -6, cmd /home/cc/rovio_ws/devel/lib/rovio/rovio_rosbag_loader __name:=rovio __log:=/home/cc/.ros/log/da3091e0-f675-11e7-979a-1c1b0de3f155/rovio-2.log].
log file: /home/cc/.ros/log/da3091e0-f675-11e7-979a-1c1b0de3f155/rovio-2*.log

                                           please help me

**Comment by x-Yabao** [comment]
if you use ros melodic, you should use yaml-cpp 0.5.2
