### ISSUE TITLE
How to get the dataset trajectory the method generated

### ISSUE THREAD

**Issue by cumtchenchang** [ethz-asl/rovio#146]
I want to evelate the method with our lab method. How to change the code to get dataset trajectory the method generated.

**Comment by bloesch** [comment]
Please have a look at the rostopic output.

**Comment by cumtchenchang** [comment]
@bloesch  Thank you for your help. I change the code folled what you said, but It dose not compile.

**Comment by Kushine** [comment]
How to get dataset trajectory the method generated?Have you got it? @cumtchenchang

**Comment by cumtchenchang** [comment]
@Kushine I got it. But I am worry it differs from the authors.

**Comment by Kushine** [comment]
In RovioNode.hpp, you can get dataset trajectory from " imuOutput_ ".

**Comment by cumtchenchang** [comment]
@Kushine  can you give me your email? my is 1253419722@qq.com

**Comment by cumtchenchang** [comment]
@Kushine  I can not change the code correctly to get the trajectory.

**Comment by Kushine** [comment]
In RovioNode.hpp, save imuOutput_ to a vector

 in RovioNode.hpp,
after line 670 imuOutputCT_.transformState(state,imuOutput_); 
add the code 
std::cout <<std::fixed<<mpFilter_->safe_.t_<< "," << imuOutput_.WrWB()(0) << "," << imuOutput_.WrWB()(1)<< "," << imuOutput_.WrWB()(2)<< std::endl;
        std::cout <<std::fixed<<imuOutput_.qBW().x()<< "," <<imuOutput_.qBW().y()<< "," <<imuOutput_.qBW().z()<< "," <<-imuOutput_.qBW().w()<< std::endl;

**Comment by Kushine** [comment]
In RovioNode.hpp, save imuOutput_ to a vector, or print as the way: 
in RovioNode.hpp,
after line 670 imuOutputCT_.transformState(state,imuOutput_);
add the code
std::cout <<std::fixed<<mpFilter_->safe_.t_<< "," << imuOutput_.WrWB()(0) << "," << imuOutput_.WrWB()(1)<< "," << imuOutput_.WrWB()(2)<< std::endl;
std::cout <<std::fixed<<imuOutput_.qBW().x()<< "," <<imuOutput_.qBW().y()<< "," <<imuOutput_.qBW().z()<< "," <<-imuOutput_.qBW().w()<< std::endl;

**Comment by cumtchenchang** [comment]
@Kushine can you give more detail? I cannot save the trajectory to txt or other files. thank you

**Comment by jixiedaima** [comment]
@Kushine  Can you tell me more?

**Comment by jixiedaima** [comment]
@Kushine  solved it, thanks!

**Comment by habib-bolourchi** [comment]
@Kushine would you tell me if imuOutput_ contains the vio answer or just the numbers that come from IMU (the device)?

**Comment by Kushine** [comment]
imuOutput_ contains the vio answer 



顾升宇   算法工程师
视辰信息科技（上海）有限公司
www.sightp.com
Email：gushengyu@sightp.com
Tel:18862918665
Add:上海市浦东新区张江镇郭守敬路498号23号楼5层
 
From: habib boloorchi
Date: 2018-08-08 03:19
To: ethz-asl/rovio
CC: Kushine; Mention
Subject: Re: [ethz-asl/rovio] How to get the dataset trajectory the method generated (#146)
@Kushine would you tell me if imuOutput_ contains the vio answer or just the numbers that come from IMU (the device)?

**Comment by better-fcl** [comment]
> In RovioNode.hpp, save imuOutput_ to a vector, or print as the way:
> in RovioNode.hpp,
> after line 670 imuOutputCT_.transformState(state,imuOutput_);
> add the code
> std::cout <<std::fixed<<mpFilter_->safe_.t_<< "," << imuOutput_.WrWB()(0) << "," << imuOutput_.WrWB()(1)<< "," << imuOutput_.WrWB()(2)<< std::endl;
> std::cout <<std::fixed<<imuOutput_.qBW().x()<< "," <<imuOutput_.qBW().y()<< "," <<imuOutput_.qBW().z()<< "," <<-imuOutput_.qBW().w()<< std::endl;

thank you very much!!!!!!

**Comment by better-fcl** [comment]
> In RovioNode.hpp, save imuOutput_ to a vector, or print as the way:
> in RovioNode.hpp,
> after line 670 imuOutputCT_.transformState(state,imuOutput_);
> add the code
> std::cout <<std::fixed<<mpFilter_->safe_.t_<< "," << imuOutput_.WrWB()(0) << "," << imuOutput_.WrWB()(1)<< "," << imuOutput_.WrWB()(2)<< std::endl;
> std::cout <<std::fixed<<imuOutput_.qBW().x()<< "," <<imuOutput_.qBW().y()<< "," <<imuOutput_.qBW().z()<< "," <<-imuOutput_.qBW().w()<< std::endl;

But i still want to know how to set the route of the result (pose.txt), can you help me? Plz, thank you!
