### ISSUE TITLE
something about the paper theory

### ISSUE THREAD

**Issue by zhuzunjie17** [ethz-asl/rovio#158]
@bloesch 
I want to know more theory about the rovio paper and i heard that your doctoral thesis provide more detailed formula. But i can't download your doctoral thesis in ETH website, could you send me your doctoral thesis? Thanks.

**Comment by bloesch** [comment]
If you have not had a look at the IJRR paper this might give some further information. Otherwise, the thesis does not include additional information as it is only a collection of papers. It was withheld due to unpublished work but will be available shortly.

**Comment by zhuzunjie17** [comment]
Thanks for your reply, I have read the IJRR paper and another EKF-based ROVIO paper. However i still can not full understand the datails of the IEKF-based method some information did not metioned on the paper(if so). So i wanna know if there are any paper you published which provide more information, or details only showed in code?
another thing is that, could you share your email to me, the email in IJRR paper is invalid.

**Comment by bloesch** [comment]
For more background understanding Barfoot's book is a great read (http://asrl.utias.utoronto.ca/~tdb/bib/barfoot_ser17.pdf). Otherwise you can also try the primer I wrote but this is rather difficult to understand (https://arxiv.org/pdf/1606.05285.pdf). The email address in the published IJRR is correct (http://journals.sagepub.com/doi/full/10.1177/0278364917728574).

**Comment by zhuzunjie17** [comment]
Thanks for your advice, its helpful.

I still cant send email to the address, strange.
![image](https://user-images.githubusercontent.com/30208773/37086095-b44fb2e8-2231-11e8-80da-20d715cb1170.png)

**Comment by bloesch** [comment]
this is the old address, please see the address in the paper on the sagepub website.
