### ISSUE TITLE
This version supports ros kinetic?

### ISSUE THREAD

**Issue by yinyanpeng** [ethz-asl/rovio#160]
This version supports ros kinetic?

**Comment by helenol** [comment]
Yes.

**Comment by yinyanpeng** [comment]
Could you show me the steps?

**Comment by ZacharyTaylor** [comment]
change to your current catkin workspace src directory and run

git clone https://github.com/ethz-asl/rovio.git
cd rovio
git submodule update --init --recursive
catkin build rovio --cmake-args -DCMAKE_BUILD_TYPE=Release -DMAKE_SCENE=ON

Then re-source your workspace and run

roslaunch rovio rovio_node.launch

**Comment by yinyanpeng** [comment]
But my ros is ros_kinectic version,not ros indigo.I can run it？

**Comment by ZacharyTaylor** [comment]
Yes.

**Comment by yinyanpeng** [comment]
Thank you very much. I just try it.

**Comment by Aishkrish18** [comment]
does it work for melodic as well?

**Comment by mzahana** [comment]
@Aishkrish18 Did you manage to make it work on later ROS versions such as melodic and noetic?
