### ISSUE TITLE
Are any datasets available?

### ISSUE THREAD

**Issue by andre-nguyen** [ethz-asl/rovio#17]
Hi,

I was wondering if there were any bag files available, or if any would be made available eventually so that I can try this out and get a feel of how it works.

Thanks

**Comment by bloesch** [comment]
We can do this. @burrimi should we provide a link to the euroc datasets?

**Comment by burrimi** [comment]
yes sure. The dataset paper finally got accepted and all the datasets are on our dataset page.
http://projects.asl.ethz.ch/datasets/doku.php?id=kmavvisualinertialdatasets

**Comment by andre-nguyen** [comment]
Thank you!

**Comment by andre-nguyen** [comment]
For anyone stumbling on this issue later, everything works great! I also had a little laugh when I saw this guy pop up from behind a table.

![12250244_10156232047690483_1844548641_o](https://cloud.githubusercontent.com/assets/6036318/11152172/11dba53e-89ff-11e5-91ab-1bd35d2cf51b.jpg)
