### ISSUE TITLE
Installation on odroid

### ISSUE THREAD

**Issue by lguanrui** [ethz-asl/rovio#181]
Hey guys, 

I'm trying to install ROVIO on Odroid XU4 but I constantly got killed during the catkin build. I have tried with catkin build -j2 or j1 but neither of them works. Here is the error I got from the catkin build: 
![screenshot from 2018-06-07 16-46-52](https://user-images.githubusercontent.com/29985917/41125517-b4a7fd66-6a72-11e8-86b5-9aa6cde2a389.png)

Hope to hear some help soon
Regards
lguanrui

**Comment by mhkabir** [comment]
Try enabling swap space.

**Comment by lguanrui** [comment]
Hey mhkabir, 

Thanks for the reply. The swap space ideas works in a way. I assigned 2GB swap space for the odroid and it still got killed when building the rovio_rosbag_node. However it successfully built without building rovio_rosbag_node. I tried to run the rovio_node with my camera but it gave me this following error, do you have any idea? 
![screenshot from 2018-06-08 15-28-26](https://user-images.githubusercontent.com/29985917/41177133-eff6daa4-6b30-11e8-9945-b35ed48116d0.png)

Hope to hear you soon
Thanks!!
lguanrui

**Comment by lguanrui** [comment]
The package successfully built after I assigned 4GB swap space!! but still it gave me the above error.

**Comment by lguanrui** [comment]
Thank you so much!! It did the trick!
