### ISSUE TITLE
ROVIO Trajectory Off by a Scale factor

### ISSUE THREAD

**Issue by lawchekun** [ethz-asl/rovio#194]
Hi,

I've been testing ROVIO on my own live camera data. It seems like the trajectory followed by the Odometry message is off by a scale factor. I observed this by moving a robot in a straight line and noticed that the trajectory by ROVIO is off as compared to the trajectory by the robot odometry.

I'm wondering what could be the likely cause for this?

Would it be a case of

1) Calibration parameters are off?

I have done my calibration with Kalibr so I believe my calibration should be fine.

Or

2) Time Synchronisation Error between camera and IMU

Please advise!

**Comment by bloesch** [comment]
There can be plenty of reasons for such an offset. Also, if you do move in a straight line only you might not be exciting the unobservable degrees of freedom properly. E.g. you IMU biases may not converge. Did you have a look at the accelerometer biases?
