### ISSUE TITLE
Error when use camera of ar drone parrot 2

### ISSUE THREAD

**Issue by chekakta** [ethz-asl/rovio#201]
I have a problem (cv_bridge exception) when use the Rovio with Ar drone camera as an input (/ardrone/image_raw).
Any help?

[ERROR] [1543498947.803930866]: cv_bridge exception: [rgb8] is a color format but [8UC1] is not so they must have the same OpenCV type, CV_8UC3, CV16UC1 ....

**Comment by odinhr** [comment]
Hi @chekakta,

I think your error is caused by the color format. You should give Rovio a grayscale image. You can convert your image to grayscale with the image_proc ROS node (http://wiki.ros.org/image_proc). Then subscribe Rovio to one of the new published topics(image_rect or image_mono). Try it!

**Comment by RigerLee** [comment]
In my case, change sensor_msgs::image_encodings::TYPE_8UC1 to sensor_msgs::image_encodings::MONO8  in imgCallback solved the problem.
