### ISSUE TITLE
HOW TO RUN ROVIO ON THE DATASET?

### ISSUE THREAD

**Issue by mechaliomar** [ethz-asl/rovio#217]
HI
PLEASE COULD SOME ONE HELP ME TO RUN ROVIO ON THE DATASET ?
I have rovio installed and I downloaded the dataset too.

THANKS

**Comment by michaelpantic** [comment]
See readme.me on the front page:

> The rovio_node.launch file loads parameters such that ROVIO runs properly on the Euroc datasets. The datasets are available under: http://projects.asl.ethz.ch/datasets/doku.php?id=kmavvisualinertialdatasets

There is a launch file that runs rovio in the proper configuration. We gladly provide support, but you need to read and understand the provided wikis and readme's (and ROS tutorials) first. 

Also we can't give meaningful support if no information on what has been tried, errors etc is given.
Maybe this helps: https://www.techsupportalert.com/content/how-ask-question-when-you-want-technical-help.htm
