### ISSUE TITLE
rovio is slow when running on bag

### ISSUE THREAD

**Issue by jakemclaughlin6** [ethz-asl/rovio#220]
ROVIO is running extremely slow on recorded bag. I've confirmed that it is something wrong with my end as it runs just fine on the Euroc datasets. I am attempting to use mavros and the pixracer board for accurate camera imu time synchronization, so I used kalibr to find the cam imu offset, then recorded my bag (using the ethz flir camera driver and mavros)
[results-imucam-2019-06-14-12-23-27.txt](https://github.com/ethz-asl/rovio/files/3306152/results-imucam-2019-06-14-12-23-27.txt). There are two main things I can see as having an effect on the speed: the fact that I'm using the sample imu noise calibration (as I havent gotten to calibrating my own yet) and that to capture the bag for the cam-imu calibration, it was running with the modified camera driver but with a cam-imu offset of 0.

**Comment by kongdaqing** [comment]
catkin_make --DCMAKE_BUILD_TYPE=Release
