### ISSUE TITLE
Position in inertial-z (altitude) seems to drift

### ISSUE THREAD

**Issue by devbharat** [ethz-asl/rovio#23]
When executing vertical motion with the camera facing down, rovio's z estimate seems to drift with respect to gazebo's ground truth with time. It happens more severely when the vertical motion is executed slowly (the slower the worse) and better when accelerations are higher.

I can observe on the Rviz output, that when rising slowly, rather than moving the IMU-Camera position estimate in the upword direction, it adjusts the tracked feature patch's location (then all start condensing closer). This doesn't happen when the vertical accelerations are higher.

Plots below:
Slow vertical motion:
![vel_test_z_slow_3d](https://cloud.githubusercontent.com/assets/3105122/11268708/92c5138a-8eb2-11e5-9092-f569f9cc7628.png)
![vel_test_z_slow_position](https://cloud.githubusercontent.com/assets/3105122/11268710/98af3c6c-8eb2-11e5-95ea-b49990ead3ee.png)
![vel_test_z_slow_linear_velocity](https://cloud.githubusercontent.com/assets/3105122/11268711/9afe86d0-8eb2-11e5-8ba3-95f51749b0ff.png)

Fast vertical motion:
![vel_test_z_3d](https://cloud.githubusercontent.com/assets/3105122/11268721/a41151c6-8eb2-11e5-9eca-7c28761d8351.png)
![vel_test_z_position](https://cloud.githubusercontent.com/assets/3105122/11268722/a7895722-8eb2-11e5-827f-d171788df411.png)
![vel_test_z_linear_velocity](https://cloud.githubusercontent.com/assets/3105122/11268725/aa3944a0-8eb2-11e5-96e5-326fec3104fa.png)

The datasets were collected with gazebo simulator, px4 sitl, and rovio position feedback.

**Comment by bloesch** [comment]
Hmmm, interesting, can you observe that effect on real data as well? you could try increasing the noise on the predicted position (in the info file).

**Comment by devbharat** [comment]
I do not have real datasets with such vertical motions (we will have some in early december). I'll try to play around with the noise parameters you mention (and others) and try to see why exactly this happens. To me it appears that when the vertical accelerations are low, for example in almost quasi-static climb, the estimator seems to trust the IMU too much (whose measurements are lost in the noise) and compensates for the change in camera image by adjusting the positions of the tracked features. Of course then it breaks down when I climb back down into the scene, almost right through the estimated feature positions.

**Comment by devbharat** [comment]
This does not happen anymore as of commit b1fd00886b731 .
