### ISSUE TITLE
Increase robustness to moving objects

### ISSUE THREAD

**Issue by burrimi** [ethz-asl/rovio#30]
When we have something moving in front of the camera, the accurracy is really bad.

**Comment by bloesch** [comment]
In the current default configuration the outlier detection is very limited. This has something to do with the pre-alignment of the patches where the predicted innovation matrix does not properly represent the noise of the innovation itself. I think the could be fixed somehow, but probably adding some dedicated outlier rejection should also be considered at some point.

**Comment by bloesch** [comment]
This was improved in the last pull request. Different parameters to make the rejection stricter or not. Should be adapted to the specific scenario.

**Comment by suyash023** [comment]
Hello! I know that this is a closed issue but can someone please tell me what are the paramters to look out for when tuning ROVIO to be robust to moving objects in the environment? I am aware that mahalanobisThreshold in the info is one such parameter. Can someone please point me to other parameters as well?
Thanks!
