### ISSUE TITLE
Wrong camera name in euroc_cam1.yaml?

### ISSUE THREAD

**Issue by andre-nguyen** [ethz-asl/rovio#31]
I noticed here https://github.com/ethz-asl/rovio/blob/master/cfg/euroc_cam1.yaml#L4 that the `cam1` configuration points to `cam0`.

```
###### Camera Calibration File For Cam 1 of Euroc Datasets ######
image_width: 752
image_height: 480
camera_name: cam0
...
```

Is this a mistake or was this done on purpose to only use the left image as described in your paper?

**Comment by bloesch** [comment]
Thanks for the note. This is just a typo and will not affect ROVIO (camera_name is not used). I'll fix it in a next commit.

In order to use a single camera only, the build variable ROVIO_NCAM can be set to 1.
