### ISSUE TITLE
Extrinsic messgae 

### ISSUE THREAD

**Issue by devbharat** [ethz-asl/rovio#39]
I suppose this in rovio_node.hpp

    ros::Publisher pubExtrinsics_[mtState::nMax_];

be

    ros::Publisher pubExtrinsics_[mtState::nCam_];

? Not important, but anyways.

**Comment by bloesch** [comment]
Definitely important, somebody might try to use a single feature with 2 cameras =)
But thanks a lot for helping getting rid of ugly little bugs like this. I'll fix it in one of the PR.
