### ISSUE TITLE
Sign of the H_ matrix

### ISSUE THREAD

**Issue by devbharat** [ethz-asl/rovio#45]
The formula used for computing the H matrix in jacState:

    F = -c_J_*featureOutputJac_.template block<2,mtState::D_>(0,0);

and in generateCandidates

    canditateGenerationH_  = c_J_*featureOutputJac_.template block<2,mtState::D_>(0,0);

I can't see why the sign is different.

**Comment by devbharat** [comment]
Also, shouldn't 

    canditateGenerationH_((int)(mtState::D_),2),

be

    canditateGenerationH_(2,(int)(mtState::D_)),

?

**Comment by bloesch** [comment]
I agree with both, thanks for the catch!
