### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by mjcarroll** [ethz-asl/rovio#51]
First, thanks for posting the video, paper, and code!

If you could, can you clarify the license that this code is available under?  The README.md indicates open-source and the package.xml indicates Proprietary.

**Comment by bloesch** [comment]
thanks for the note, I should have made this clearer from the start. the code is under the BSD license. clarified it in the readme/package.xml and added a license file.

**Comment by mjcarroll** [comment]
Thanks!
