### ISSUE TITLE
SrvResetToPose.h missing

### ISSUE THREAD

**Issue by sc38514** [ethz-asl/rovio#64]
RovioNode.hpp requires SrvResetToPose.h, but I can't find this header file anywhere.
Am I missing something?

fatal error: rovio/SrvResetToPose.h: No such file or directory
 #include <rovio/SrvResetToPose.h>

**Comment by bloesch** [comment]
Did you use catkin tools to build? This header should automatically get generated.

I just tried a fresh install on my system and it also complained at the first attempt. Try building it twice.

**Comment by sc38514** [comment]
Confirmed after a clean install of Ubuntu 14.04 and ROS indigo the compilation was successful on the second build run.

**Comment by bloesch** [comment]
Closing this - unless somebody else got the same issue.
