### ISSUE TITLE
error compiling on ubuntu 14.04

### ISSUE THREAD

**Issue by blankered** [ethz-asl/rovio#71]
I am having trouble compiling rovio on my laptop. I have installed the lightweight_filtering, kindr, and updated my opencv links. Here is my current error log...

[build.make.052.log.txt](https://github.com/ethz-asl/rovio/files/350391/build.make.052.log.txt)

**Comment by bloesch** [comment]
There has been a recent update in the kindr library. Did you pull the newest master branches in both repos, rovio and kindr? lightweight_filtering is included as submodule in rovio, so this should already match with the rovio version.

**Comment by blankered** [comment]
Thanks, downloaded the new vision and it worked!

**Comment by bloesch** [comment]
Thanks for the note. Closing.
