### ISSUE TITLE
Error opening file? 

### ISSUE THREAD

**Issue by sc38514** [ethz-asl/rovio#72]
I'm using Ubuntu 14.04 with ROS indigo.

The launch file is set to run only one camera and the IMU and camera topics are remapped to the corresponding topics in my bag file.

The error shows:

Recording
Storing output to: /path/to/file.bag
terminate called after throwing an instance of 'rosbag::BagIOException' 
 what(): Error opening file: /path/to/file.bag

Anyway to resolve this?

Thanks.

**Comment by mhkabir** [comment]
You're supposed to use the actual path to the bagfile instead of "/path/to/file.bag"

**Comment by sc38514** [comment]
Actually I just censored the path/file name due to an NDA, but the path to bagfile was specified.
However I don't think reading/playing from my bagfile is causing the error because the error is from opening the file to record:

what(): Error opening file: /some/path/rovio/2016-07-12-01-45-12_25_4_6_1_0.bag

where the folder /some/path/ is where my bags are stored, the /rovio folder I assume is created by rovio node, and 2016-07-12-01-45-12_25_4_6_1_0.bag looks like a timestamped file also generated from the rovio node.

**Comment by bloesch** [comment]
I think you have to pre-create the rovio folder manually. this is an issue that should get slved in the future.

**Comment by andrejpan** [comment]
When I ran rovio_rosbag_node.launch I also had the same problem. After making rovio folder package started working.

**Comment by Denfender** [comment]
I have the same problem with you when running rovio_rosbag_node.launch,how do you solve it ?Thanks

**Comment by Denfender** [comment]
@andrejpan hope your advice

**Comment by bloesch** [comment]
if you get:
  what(): Error opening file: /some/path/rovio/my.bag
do:
  mkdir /some/path/rovio

**Comment by Denfender** [comment]
Thanks for reply! but i doesnot understand. I have put my bag into the path where the launch file inculded.
I think this cannot solve my problem.Does  this bag should put into "rovio" file?@bloesch

**Comment by bloesch** [comment]
You might have a different error. Did you try building in debug mode? What error do you get?

**Comment by Denfender** [comment]
thank you .it works.I should build in debug mode. thank you !also ,opengl shuold be used for view.thank you @bloesch

**Comment by bloesch** [comment]
just be sure to switch back to release mode

**Comment by karanchawla** [comment]
I created the "rovio" folder in my /karan/Downloads/ directory. I still get this error. What am I missing? 

https://snag.gy/60zYoe.jpg

Thank you!

**Comment by Denfender** [comment]
@karanchawla ，this is a common problem.you can change the permissions. if it dosenot work ,you should use a absolute path .in a word ,you can also rosplay this bag,not using the  rovio_rosbag_node.launch.

**Comment by Kyle-ak** [comment]
@Denfender Could you tell me how you made rovio work? I'm new to ROS, where should I create the "rovio" folder? And I really couldn't get a clue the error I was informed of:

Recording
open file:</home/ak/workspace/rovio_catkin_ws/src/rovio/dataset.bag>
terminate called after throwing an instance of 'rosbag::BagIOException'
  what():  Error reading version line
Aborted (core dumped)

**Comment by bloesch** [comment]
@Kyle-ak can you check your bag file? try rosbag info dataset.bag ...

Otherwise, please build in debug mode to get a more details.

**Comment by Kyle-ak** [comment]
@bloesch Thanks for your reply, it's indeed the rosbag file... One of the two files is corrupted. Now I can get it running on the _MHMH_03_medium.bag_. However, another problem popped up. I got the warning:

==== Model jacInput Test failed: 74.0615 is larger than 1 at row 1(def_0) and col 0() ====

And the feature tracking part seems fine, but the Scene is static all the time. 

![screenshot](https://cloud.githubusercontent.com/assets/13564326/21219692/c34cca0c-c2f0-11e6-9747-e5c207d35eea.png)

**Comment by better-fcl** [comment]
> I think you have to pre-create the rovio folder manually. this is an issue that should get slved in the future.

thank you!
