### ISSUE TITLE
Using GLSL 3.00 ES

### ISSUE THREAD

**Issue by devbharat** [ethz-asl/rovio#8]
Can the shader files be modified to use GLSL version 3.00 ES easily ?
Or can the node be compiled to not require the graphic output used by the shaders ?

Thanks.

**Comment by bloesch** [comment]
GLSL 3.3 is required for visualizing the 3D scene. However, you can compile the node without the DMAKE_SCENE flag. Only the image visualization will be supported in that case. Should be enough for most applications...

**Comment by devbharat** [comment]
Actually, I made very minor modifications to the shader files to work with GSLS 3.0 ES, it seems to run properly. I can make a PR if you wish.

I am not sure if GLSL 3.3 run on ubuntu with intel graphics.

**Comment by bloesch** [comment]
That would be nice. thanks

**Comment by devbharat** [comment]
https://github.com/ethz-asl/rovio/pull/12
