### ISSUE TITLE
Interesting new stereo cam + IMU offering

### ISSUE THREAD

**Issue by nicolov** [ethz-asl/rovio#84]
I've just found this interesting off-the-shelf product with a global shutter stereo camera and integrated IMU. Now that the the VI sensor is no longer for sale, it could be an easy solution for rovio, at $249.

[link](https://www.e-consystems.com/3D-USB-stereo-camera.asp)

While the cameras are synchronized, the spec sheet doesn't say anything about the IMU sync. However, since everything is delivered over the same USB3 connection, you'd think the time delay would be pretty stable, and thus correctable.

**Comment by mhkabir** [comment]
Nice! I like it :)

**Comment by Changliu52** [comment]
This is perfect!

**Comment by gajena** [comment]
Have anyone tried this one?

**Comment by mzahana** [comment]
Any one tried this camera?

**Comment by jm677zz** [comment]
I have tried this camera. The IMU and the frame time is not synced, they provide few applications based on OpenCV to evaluate the camera and IMU.

**Comment by nicolov** [comment]
Yeah, the IMU is out of sync, and sometimes you get duplicate samples. I had to write my own IMU driver as the sample code was not great.

I also found this other option, but haven’t tried it yet: https://m.seeedstudio.com/productDetail/2873

**Comment by mzahana** [comment]
@nicolov thanks for the reply.

For the Optor cam you mentioned. I could not find it's corresponding SDK and its ROS wrapper although it's claimed to have them.

I have not tried that cam, so I don't have feedback about it either.

**Comment by mzahana** [comment]
After some search, I found the Optor SDK.
https://github.com/optor-vis/vi-stereo-v1
