### ISSUE TITLE
Lock the bearing vectors

### ISSUE THREAD

**Issue by meyiao** [ethz-asl/rovio#86]
Hi, I learned that in paper: E. S. Jones and S. Soatto, “Visual-inertial navigation, mapping and localization: A scalable real-time causal approach”,  the authors keep the features' bearing vector constant, so that only a depth parameter is needed for one feature. This could greatly reduce the state vector size.  I think it may help reduce the computational cost.

**Comment by bloesch** [comment]
maybe I missunderstood it, but they still estimate the projection of landmarks into the initial frame y_0^i. Also, in context of rovio I am not sure how one could get rid of the bearing vector estimation. You can  do the landmark tracking outside the filter but then you loose the nice property of tightly binding the IMU measurements into the data association.
