### ISSUE TITLE
NO Time synchronizer

### ISSUE THREAD

**Issue by Denfender** [ethz-asl/rovio#90]
I want to run rovio without time synchronizer.how can i do for it ?hope someone give me advice!
or someone do this successly.

**Comment by bloesch** [comment]
you need proper timestamping, otherwise rovio will not work. To be more specific: the timestamps in the IMU msg and the Image msg need to be given w.r.t. the same clock.

**Comment by Denfender** [comment]
thank for your reply! i will try,but i read the code which is loosely coupled,but the paper is tight coupled ,what 's wrong with it ?@bloesch

**Comment by bloesch** [comment]
i do not understand the link to loosely/thightly coupled. this has nothing to do with time synchronization
