### ISSUE TITLE
State vector and IMU propagating code

### ISSUE THREAD

**Issue by pangfumin** [ethz-asl/rovio#91]
Hi all,

Thx for sharing the code! It is impressive! 
I spend some time to read your paper and code , and get a little confused with the state vectors. Them seem to be a little different between paper and c++ code . For example in paper, r is used for expressing imu position in IMU frame. but in the code this state part is defined as WrWM ( expressed in World frame).

Plus, the IMU propagation process is also a little different from paper.

Can you give me more detail about the state vector and propagation part uesed in the code? I hope I do not misunderstand!

Thank you again.

**Comment by bloesch** [comment]
There is some difference between code and IROS 2015 paper as there were a couple of updates. There is a new paper which is more up to date but this is still under review.

Best is if you understand the notation in the code, i.e., ArBC is the vector pointing from B to C expressed in A and qAB is the quaternion describing the rotation from B to A.

Maybe the following paper helps a bit for understanding the notation and how the different derivatives are computed:
https://arxiv.org/abs/1606.05285
