### ISSUE TITLE
Add a simple demo example

### ISSUE THREAD

**Issue by rdube** [ethz-asl/rovio#93]
Would it be possible to add a simple demo example for using rovio eg. with the euroc dataset? It can be very short, just the launch files or nodes which needs to be launched. Is that information already somewhere? Thanks!

**Comment by burrimi** [comment]
I think you can adapt this launchfile to point to the correct bag location.
https://github.com/ethz-asl/rovio/blob/master/launch/rovio_rosbag_node.launch

**Comment by burrimi** [comment]
it looks like also the default launchfile uses the euroc dataset calibration.
launch this
https://github.com/ethz-asl/rovio/blob/master/launch/rovio_node.launch 
and play the bag in another terminal

**Comment by rdube** [comment]
Yes thanks for the info! We will give it another try! Would it help to add this short piece of information in the readme somewhere?

**Comment by burrimi** [comment]
it's already in the readme :)

> Euroc Datasets
> 
> The rovio_node.launch file loads parameters such that ROVIO runs properly on the Euroc datasets. The datasets are available under: http://projects.asl.ethz.ch/datasets/doku.php?id=kmavvisualinertialdatasets

**Comment by rdube** [comment]
Fair enough! Thanks! ;)

**Comment by Kyle-ak** [comment]
@burrimi Could you tell me how to run rovio on the Euroc dataset? I launched the rovio_node, and then rovio_rosbag_node, but always got the error msg:
      terminate called after throwing an instance of 'rosbag::BagIOException'
      what():  Error reading version line
I have already changed the path in the "rovio_rosbag_node.launch",  still this error keeps coming up. I'm quite new to ros, and I really couldn't find much info about this error.

**Comment by bloesch** [comment]
See answers in #72
