### ISSUE TITLE
Catkin build issue with 16.04

### ISSUE THREAD

**Issue by marija-p** [ethz-asl/rovio#99]
Hi,

I just thought I would let you know that I recently encountered an issue attempting to catkin build Rovio with ROS Kinetic on my Ubuntu Linux 16.04 operating system and Lenovo X1 Yoga laptop. Basically, the system refused to build the packages due to a compatibility problem with yaml-cpp versions; it said that some lines of code have been deprecated in the version it was looking for (I do not have further details on the build error unfortunately as I do not have access to my bash history). I managed to solve the problem by catkin building using the 'force' catkin build flag. Strangely the package then compiled without a problem.

`catkin build rovio --force-cmake`

I encountered this issue twice on fresh Ubuntu 16.04 installs, using the same machine.

Hope this provides some insight as to how rovio compatibility can be improved,

Marija

**Comment by bloesch** [comment]
thank you for the note. yaml-cpp has already caused version issues in the past (#44). not yet sure what we should do in the future.
